name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
    pull_request:

jobs:
  compliance_io:
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.4

      - name: View poetry --help
        run: poetry --help

      - name: Build
        run: poetry build
